# Hello, world!
#
# This is an example function named 'hello'
# which prints 'Hello, world!'.
#
# You can learn more about package authoring with RStudio at:
#
#   http://r-pkgs.had.co.nz/
#
# Some useful keyboard shortcuts for package authoring:
#
#   Build and Reload Package:  'Ctrl + Shift + B'
#   Check Package:             'Ctrl + Shift + E'
#   Test Package:              'Ctrl + Shift + T'

hello <- function() {
  print("Hello, world!")
}

#' Get Results from Arena CSV Files
#'
#' This function reads all csv files inside the provided path and returns a data.frame with the simulation runs, consolidated.
#' You should provide a path containing only csv files generated by Arena. I Suggest you to name your csv files after your scenarios.
#'
#' @param path The path where csv files is stored. If you do not provide a value, I'll assume they're on your current working directory.
#'
#' @return a tidy dataframe with simulation results.
#' @export
#'
get_simulation_results = function(path) {


  if (missing(path)) {
    path = getwd()
  }

  caminho_arquivos = paste(path, list.files(path = path,pattern = ".csv"), sep = "/")
  nomes_cenarios <- list.files(path = path,pattern = ".csv")
  nomes_cenarios = gsub(".csv", "", nomes_cenarios)

  for (i in 1:length(nomes_cenarios)) {

    dados_cenario = read.csv(file = caminho_arquivos[i])

    dados_cenario$Scenario = nomes_cenarios[i]

    if(i == 1) {
      dados_completos = dados_cenario
    } else {
      dados_completos = rbind(dados_completos, dados_cenario)
    }

  }

  # Definindo Cenario como um Fator:
  dados_completos$Scenario = as.factor(dados_completos$Scenario)

  # Trazendo coluna dos Cenarios para a Frente:

  dados_completos = dados_completos[,c(length(names(dados_completos)), 1:(length(names(dados_completos))-1))]

  # Empilhando os Dados para Facilitar as Coisas

  dados_empilhados = dados_completos %>% tidyr::gather(key = Replication, value = Valor, 7:length(names(dados_completos)))

  dados_empilhados

}

